/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Lightweight liveness/health check. No auth, no parameters. Useful for verifying the app <-> backend wiring and for monitoring, independent of the main /ask logic.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the AI about the current location (mock stage)
         * @description Send the current location (and, later, the recorded audio) and get an answer back. At the mock stage this returns a fixed answer and echoes the received points. STT/LLM/TTS and API-key auth are added later.
         */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A GPS point. */
        Coordinates: {
            /**
             * Format: double
             * @example 35
             */
            latitude: number;
            /**
             * Format: double
             * @example 139
             */
            longitude: number;
        };
        /** @description Request body for POST /ask. `start` and `end` are the two GPS points taken around the recording; the direction of travel is derived from them (see 01_architecture.md). */
        AskRequest: {
            start: components["schemas"]["Coordinates"];
            end: components["schemas"]["Coordinates"];
        };
        /** @description Response body for POST /ask (mock stage). */
        AskResponse: {
            /**
             * @description Status message (mock marker).
             * @example mock backend is alive
             */
            message: string;
            /**
             * @description The answer to read back to the user.
             * @example これはモックの回答です。バックエンド連携が通っています。
             */
            answer: string;
            /** @description Echo of the received points (mock only; removed later). */
            received?: {
                start?: components["schemas"]["Coordinates"];
                end?: components["schemas"]["Coordinates"];
            };
        };
        ErrorResponse: {
            /** @description Human-readable error message. */
            error: string;
        };
        HealthResponse: {
            /**
             * @description Health status.
             * @example ok
             */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Answer generated (mock) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Invalid request (e.g. malformed body) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
