/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Lightweight liveness/health check. No parameters.
         *     ⚠️ The one endpoint that takes NO API key. A liveness check that needed a secret could not answer "is the API up, or is my key wrong?", which is what it gets reached for. It calls no billable service.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a question about the current location
         * @description Send a question together with the current location. The answer is NOT returned here: generating it takes 10-25s, which does not fit inside API Gateway's 29s ceiling once speech is added, so the question is queued and answered in the background.
         *     The response is 202 with a `requestId`. Poll GET /ask/{requestId} until its status is `done` or `error`.
         *     Pass the same `sessionId` on later requests to continue the conversation (US-1.02). Voice (STT/TTS) comes later.
         */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Collect the answer to a queued question
         * @description Poll this after POST /ask until `status` is `done` or `error`; while it is `pending` the answer is still being generated.
         *     The app backs its polling off (1s, then 2s, then 4s) and gives up after 80 seconds - measured answers take 10-13s, so anything much beyond that has gone wrong.
         *     Note that a failed question is reported as 200 with `status: "error"`, not as an HTTP error: the request itself succeeded.
         */
        get: operations["getAskResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A GPS point. */
        Coordinates: {
            /**
             * Format: double
             * @example 35
             */
            latitude: number;
            /**
             * Format: double
             * @example 139
             */
            longitude: number;
        };
        /**
         * @description Request body for POST /ask.
         *     `start` is the rider's current location, and the point the address is resolved from. `end` is an EARLIER position, used to derive the direction of travel: the rider is travelling away from `end` towards `start`. It stays optional - the server simply omits the heading when it is missing, or when the two points are within a few metres of each other (a rider stopped at a light, where the bearing would be GPS noise).
         */
        AskRequest: {
            /**
             * @description The rider's question, as text.
             * @example 右手に見える山は何ですか？
             */
            question: string;
            /**
             * @description Conversation id. Omit it to start a new conversation - the server mints one and returns it. Send that value back to continue the conversation. The app's job is to store it, not to generate it. (At least 33 characters, an AgentCore requirement.)
             * @example touring-0123456789abcdef0123456789abcdef
             */
            sessionId?: string;
            /** @description The rider's current position. */
            start: components["schemas"]["Coordinates"];
            /** @description An earlier position, for the direction of travel (US-2.03). The app picks it by walking back through its recent fixes for the newest one far enough away to give a meaningful bearing, and omits it entirely when there is none - while stopped, or just after a turn, where a heading would be stale or change second to second. */
            end?: components["schemas"]["Coordinates"];
            /**
             * Format: int32
             * @description Seconds since the first question of this conversation. Lets the agent tell how much the rider has moved between turns, so it can resolve "that mountain" against the position it was asked at rather than the current one. Omit on the first question of a conversation.
             * @example 180
             */
            elapsedSeconds?: number;
        };
        /** @description Response body for POST /ask. The question has been queued, not answered - fetch the answer from GET /ask/{requestId}. */
        AskAcceptedResponse: {
            /**
             * @description Id to poll GET /ask/{requestId} with.
             * @example 3f1c9a2e-5b7d-4e6a-9c81-0d2f4b6a8e13
             */
            requestId: string;
            /**
             * @description The conversation id this question belongs to. Echoed back so the app can store it and continue the conversation on the next request (it is the server that generates one when the app sends none).
             * @example touring-0123456789abcdef0123456789abcdef
             */
            sessionId: string;
        };
        /** @description Response body for GET /ask/{requestId}. */
        AskResultResponse: {
            /**
             * @description `pending` means keep polling. `done` means `answer` is present; `error` means `error` is, and the question will not be answered.
             * @example done
             * @enum {string}
             */
            status: "pending" | "done" | "error";
            /**
             * @description The answer to read back to the rider. Present when done.
             * @example それはたぶん富士山です。標高は3776メートルあります。
             */
            answer?: string;
            /**
             * @description Why the question could not be answered. Present when the status is `error`. Safe to show to the rider.
             * @example The agent could not be reached.
             */
            error?: string;
            /**
             * @description The conversation id this question belongs to.
             * @example touring-0123456789abcdef0123456789abcdef
             */
            sessionId: string;
        };
        ErrorResponse: {
            /** @description Human-readable error message. */
            error: string;
        };
        HealthResponse: {
            /**
             * @description Health status.
             * @example ok
             */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Question accepted and queued. Poll GET /ask/{requestId} for the answer. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskAcceptedResponse"];
                };
            };
            /** @description Invalid request: malformed body, missing/empty `question`, a question over the length limit, or a `sessionId` shorter than 33 characters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description The API key is missing or wrong.
             *     ⚠️ API Gateway also returns 403 - not 404 - for a path that is not deployed, so this status does not prove the key is at fault. See Backend/README.md for telling the two apart.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The usage plan's limit was hit: either the daily quota or the per-second rate. The two are not distinguishable from the response. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The question could not be accepted for processing. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAskResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id returned by POST /ask. */
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state of the question. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResultResponse"];
                };
            };
            /** @description No `requestId` was given. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The API key is missing or wrong (see POST /ask). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such request. Also returned once the record has expired, an hour after it was created. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description The usage plan's limit was hit.
             *     ⚠️ The app does NOT give up on this while polling - it polls once a second, so a brief brush with the rate limit is expected and the next attempt usually succeeds.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The stored result could not be read. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
