/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Lightweight liveness/health check. No auth, no parameters. Useful for verifying the app <-> backend wiring and for monitoring, independent of the main /ask logic.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the AI about the current location
         * @description Send a question together with the current location and get the answer back. The Lambda forwards this to the AgentCore runtime, which handles the conversation history and web search.
         *     Pass the same `sessionId` on later requests to continue the conversation (US-1.02). Voice (STT/TTS) and API-key auth come later.
         */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A GPS point. */
        Coordinates: {
            /**
             * Format: double
             * @example 35
             */
            latitude: number;
            /**
             * Format: double
             * @example 139
             */
            longitude: number;
        };
        /**
         * @description Request body for POST /ask.
         *     `start` is the rider's current location. `end` is the second GPS point used to derive the direction of travel; it is optional because heading is US-2.03 and outside the MVP.
         */
        AskRequest: {
            /**
             * @description The rider's question, as text.
             * @example 右手に見える山は何ですか？
             */
            question: string;
            /**
             * @description Conversation id. Send the same value to continue the previous conversation; omit it to start a new one. The app generates and stores this (at least 33 characters, an AgentCore requirement).
             * @example touring-0123456789abcdef0123456789abcdef
             */
            sessionId?: string;
            start: components["schemas"]["Coordinates"];
            end?: components["schemas"]["Coordinates"];
        };
        /** @description Response body for POST /ask. */
        AskResponse: {
            /**
             * @description The answer to read back to the rider.
             * @example それはたぶん富士山です。標高は3776メートルあります。
             */
            answer: string;
            /**
             * @description The conversation id this answer belongs to. Echoed back so the app can store it and continue the conversation on the next request (it is the server that generates one when the app sends none).
             * @example touring-0123456789abcdef0123456789abcdef
             */
            sessionId: string;
        };
        ErrorResponse: {
            /** @description Human-readable error message. */
            error: string;
        };
        HealthResponse: {
            /**
             * @description Health status.
             * @example ok
             */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Answer generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Invalid request: malformed body, missing/empty `question`, a question over the length limit, or a `sessionId` shorter than 33 characters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The agent could not be reached or returned no answer. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
